name: CD - Deploy to Dev Environment

on:
  workflow_run:
    workflows: ["CI Pipeline with Security & Quality Scans"]
    types:
      - completed

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render (Dev)
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-d2oo2eogjchc73f0gjtg/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json"
